getwd()
setwd("/home/pauescarcia/Documentos/BigDataZacatecas/BigData-Zacatecas/section1/1.6 More Ways to Acquire and Inspect Data")
dir()
temp <- read.csv("3dtco.csv")
head(temp)
str(temp)
aggregate(reltco~subsystem, data=temp, FUN=mean)
aggregate(reltco~subsystem, data=temp, FUN=list)
aggregate(reltco~subsystem, data=temp, FUN=length)
aggregate(reltco~subsystem, data=temp, FUN=sum)
aggregate(reltco~subsystem, data=temp, FUN=is.na)